### ISSUE TITLE
DrawFlow with angular and button with event

### ISSUE THREAD

**Issue by WilliamCampolina** [RoyaghRamo/angular-drawflow-example#1]
guys, I'm using it in a project with angular following the following examples from this project 
but I can't do the action on a button on the node, it says it can't find the function. Can anyone help me because I can't. thank you so much

![image](https://user-images.githubusercontent.com/7756498/190183381-96a89745-80b3-4402-a84b-06d097337623.png)

**Comment by RoyaghRamo** [comment]
Hello, try using the "click" event of the editor, and program as you see fit.
Here is something I've used
![image](https://user-images.githubusercontent.com/57964781/190186541-a70e6395-35f0-4989-91ce-3059d6b8cf8a.png)

**Comment by WilliamCampolina** [comment]
thank you very much, this will help me... it worked

**Comment by RoyaghRamo** [comment]
> thank you very much, this will help me... it worked

You're welcome mate

**Comment by WilliamCampolina** [comment]
one last thing, I didn't understand how the showpopup opened the modal, that way it didn't work

reference
https://github.com/jerosoler/Drawflow/blob/master/docs/index.html

**Comment by RoyaghRamo** [comment]
> one last thing, I didn't understand how the showpopup opened the modal, that way it didn't work
> 
> reference https://github.com/jerosoler/Drawflow/blob/master/docs/index.html



In Angular, you can create a popup using ModalRef.
Sorry for the late reply.
