### ISSUE TITLE
Number of Input/Output not changing

### ISSUE THREAD

**Issue by Jeronimo59** [RoyaghRamo/angular-drawflow-example#2]
Thank you for this.

When I change either Inputs or Outputs values, nothing changes on the shapes...

Is there an action to refresh the diagram ? Do I miss something ?

**Comment by RoyaghRamo** [comment]
That I/O doesn't affect the diagram, but it affects the process that's being used to create the dataflow json.

**Comment by Jeronimo59** [comment]
Sorry. I didn't realize I could drag & drop the nodes on the left ... it works fine :-) !

**Comment by RoyaghRamo** [comment]
Great, enjoy it, it's only a tutorial
